---
country_code: tz
aws_region: eu-west-1
database: "loans"
database_qa: "loans_qa"
database_qa2: "loans_qa2"
database_staging: "loans_staging"
database_demo: "loans_demo"
database_dev: "loans_dev"
internal_databases:
  - loans_qa
  - loans_qa2
  - loans_dev
  - loans_staging
  - loans_demo
source_db_host: "eu-ireland-maindb.c2ouxvpejoh2.eu-west-1.rds.amazonaws.com"
target_db_host: "internal-testing-db-eu1.c2ouxvpejoh2.eu-west-1.rds.amazonaws.com"
tables: "tables"
archive_database: loans
source_db_username: "{{ vault_tz_source_db_username }}"
target_db_username: "{{ vault_tz_target_db_username }}"
source_db_password: "{{ vault_tz_source_db_password }}"
target_db_password: "{{ vault_tz_target_db_password }}"
archive_db_password: "{{ vault_tz_archive_db_password }}"
archive_db_username: "{{ vault_tz_archive_db_username }}"
archive_db_host: "eu-ireland-maindb.c2ouxvpejoh2.eu-west-1.rds.amazonaws.com"

sns_arn: "arn:aws:sns:eu-west-1:347023968887:tz-aws-alerts"
